### ISSUE TITLE
Thank you soo much for this port!

### ISSUE THREAD

**Issue by emanuel-macoun** [suomipelit/ultimatetapankaikki-web#1]
[This is not bug report]

I just want to thank you for bringing me 20 years into the past! We played this incredible game while I was at college - we spent sleepless nights (boosted with all kinds of substances) playing this game. Also, when multiplayer was mainly deathmatch,  it was one of the rare games where coop multiplayer actually made sense.

Thanks again and if you by a chance show up in Prague, don't hesitate to ping me. I'll be more than happy to buy you tenbeer ;)

Eman

**Comment by veikkos** [comment]
Thank you for the kind feedback and nostalgia! Really appreciated. I hope you have as fun playing as I've had while porting.
